AllCops:
  TargetRubyVersion: 2.6

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: double_quotes

Metrics/ClassLength:
  Enabled: false

Layout/LineLength:
  Max: 120

Metrics/MethodLength:
 Max: 100
 CountAsOne: ['array', 'hash', 'heredoc']
